### ISSUE TITLE
切换国家的时候大概率会出错

### ISSUE THREAD

**Issue by darenpang** [Adonis142857/Real-Address-Generator#2]
Failed to retrieve detailed address, please refresh the interface （检索详细地址失败，请刷新界面）

也有成功的时候。体感70%以上会出错

**Comment by Adonis142857** [comment]
这个问题是一般是由“随机位置生成范围有限”导致的，我目前考虑到了两种方案
1. 增加随机偏移的范围，比如从 ±0.05 度增加到 ±0.5 度
2. 增加尝试次数，比如将尝试次数从 20 次增加到 50 次
考虑到扩大偏移范围可能会导致生成海洋或无人区，我将在下一版本中采用增加尝试次数的方案，感谢你的反馈
